title: Woonyong Blog
description: 개발과 운영을 기록하는 블로그
url: "https://blog.woonyong.org"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul
markdown: kramdown
highlighter: rouge
permalink: /:title/

analytics:
  google:
    measurement_id: ""

comments:
  provider: "giscus"
  disqus:
    shortname: ""
  giscus:
    repo: "woonyong-kr/woonyong-kr.github.io"
    repo_id: "R_kgDOR9z4JQ"
    category: "Announcements"
    category_id: "DIC_kwDOR9z4Jc4C6cIf"
    mapping: "pathname"
    strict: true
    reactions_enabled: true
    emit_metadata: false
    input_position: "bottom"
    lang: "ko"
    loading: "lazy"
    theme_light: "/assets/css/giscus-velog-light.css"
    theme_dark: "/assets/css/giscus-velog-dark.css"

search:
  provider: local
  algolia:
    app_id: ""
    api_key: ""
    index_name: ""
    insights: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "assets"
    values:
      layout: null
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - LICENSE
  - NOTICE.md
  - README.md
  - output
  - scripts
  - vendor
