title: Velog Style Jekyll Theme
description: velog 감성의 개발 블로그를 GitHub Pages와 Jekyll로 구성한 오픈소스 테마 데모
url: "https://blog.woonyong.org"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul
markdown: kramdown
highlighter: rouge
permalink: /:title/

analytics:
  google:
    measurement_id: ""

comments:
  provider: "giscus"
  disqus:
    shortname: ""
  giscus:
    repo: "woonyong-kr/jekyll-theme-velog"
    repo_id: "R_kgDOR1XW1w"
    category: "Announcements"
    category_id: "DIC_kwDOR1XW184C570c"
    mapping: "pathname"
    strict: true
    reactions_enabled: true
    emit_metadata: false
    input_position: "bottom"
    lang: "ko"
    loading: "lazy"
    theme_light: "light"
    theme_dark: "transparent_dark"

search:
  provider: local
  algolia:
    app_id: ""
    api_key: ""
    index_name: ""
    insights: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "assets"
    values:
      layout: null
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - LICENSE
  - NOTICE.md
  - README.md
  - output
  - scripts
  - vendor
